# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='static_files/uploaded/original/%Y/%m/%d')),
                ('filtered_image_file', models.ImageField(upload_to='static_files/uploaded/filtered/%Y/%m/%d')),
                ('description', models.TextField(max_length=1000)),
                ('realease_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
