# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bread',
            old_name='realease_at',
            new_name='release_at',
        ),
    ]
