# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_auto_20160229_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='filtered_image_file',
            field=models.ImageField(upload_to='filtered/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bread',
            name='image_file',
            field=models.ImageField(upload_to='original/%Y/%m/%d'),
        ),
    ]
