# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0003_auto_20160229_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='name',
            field=models.TextField(default='noname'),
        ),
    ]
