# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0004_bread_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='release_at',
            field=models.DateTimeField(default=b'Thu Mar  3 15:02:25 2016'),
        ),
    ]
