# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0005_auto_20160303_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 1, 0, 0)),
        ),
    ]
