# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0008_auto_20160303_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
